### PR TITLE
Unique filenames

### PR DESCRIPTION
**Pull request by tymmej**
Contains #146 as otherwise that option isn't useful.

### CODE REVIEW

**Comment by mandarons** [comment]
Does this PR make #146 and #145 obsolete?

**Comment by tymmej** [comment]
This PR contains them.

I split them to smaller chunks to reduce scope and allow smaller merges.
- #145 - bug fix
- #146 - new feature
- #148 - add on to #146, without #146 merged #148 isn't useful

**Comment by mandarons** [comment]
@tymmej When `all_albums` is `true`, it will create nested folders for each album. That will create unique paths for photos that are present with same name in multiple albums. 

@tymmej  Why do we need this PR?

**Comment by tymmej** [comment]
I'm using downloaded photos with https://github.com/photoview/photoview

Photoview has bug (or maybe it's intentional?) that photos in database are stored only by filename - not full path. So it doesn't work with multiple files with same filename, but in different folders.
Photoview displays folders as albums in web view, but if same photo is added to multiple albums in iCloud then it's visible only in one album in web view.
Adding this option allows to show photo in all albums.

**Comment by mandarons** [comment]
@tymmej: Okay. Yeah, I remember this use case. This is a one-off use case and doesn't matter for broader user base of this tool. I am not planning to spend any time in maintaining one-off use cases at this point. However, I can get this feature in, given that it is enabled by a flag in config and how important it is to you. 

Going forward, would you like to be the maintainer of this feature?

**Comment by tymmej** [comment]
What "maintainer" does mean in this context?

Can this pull request wait? Immich made some progress with read-only libraries (https://documentation.immich.app/docs/features/libraries). It is not ideal at the moment - it doesn't  create albums from folders, but maybe it will be added (https://github.com/immich-app/immich/discussions/4279). Also it seems that Immich has larger user base so I'm planning to migrate to it.

**Comment by mandarons** [comment]
@tymmej Maintainer for a feature is typically a go to person to get help from, should any issue arise in using the feature (i.e. helping with resolving bugs related to the feature).

Yeah, this PR can certainly wait. I only heard good things about immich. It seems to be trending to the top in FOSS photos management and being very actively developed. I certainly recommend migrating to immich.

**Pull request closed without merging**
