### PR TITLE
Fix same names of photos, save all albums, fix package with remove_obsolete

### PR DESCRIPTION
**Pull request by tymmej**
See issue 98, 99 and 100.

It could be improved by adding hash to filename only when there's conflict.

I skip "All albums" folder because in my case all photos belongs to (at least) one folder.

### CODE REVIEW

**Comment by tymmej** [comment]
Unfortunately, icloudpy does not handle nested folders :(

I have following structure:
2022:
  - 2022-01-Event 1
  - 2022-01-Event 2
  - 2022-03-Event N

API returns no photos (correct), but also no subalbums :( 
```
>>> api.photos.albums['2022']
<PhotoAlbum: '2022'>
```

**Comment by tymmej** [comment]
I created pull request in library to support nested forked and updated sync_photos.py

**Comment by mandarons** [comment]
Please fix build failures.

**Comment by tymmej** [comment]
I see two problems in CI:
1) drive sync: one file cannot be downloaded - do you know why?
2) photo sync:
a) I only add hash to original filename, not thumbnail
b) Tests expect original filename not with added hash

How do you see resolution to issue #98? I added hash because it works for me.
But I'm not sure if it is the best solution.
One alternative is to use `photo.id` but then file structure would be completely unreadable to user. But filenames will be unique.

**Comment by mandarons** [comment]
@tymmej : can you please split this PR into three separate PRs, one for each - Fix same name of photos, save all albums and fix package with remove_absolete? It's hard for me to follow the code and provide review comments.

**Comment by tymmej** [comment]
I've created new pull request with `fix package with remove_absolete`.

I will make pull requests for other issues after merging this.

**Pull request closed without merging**
